import { BaseEntity, Column, Entity, Index, JoinColumn, OneToOne, PrimaryGeneratedColumn } from "typeorm";
import { User } from "./user";


/** 
 * ! need to implement not working because typeorm doesn't allow as of now
 */
enum visibilityOption {
    public,
    private,
}

@Entity()
export class Room extends BaseEntity {

    /**
     * Room id ..auto generated by db
     */
    @Index()
    @PrimaryGeneratedColumn()
    id: number;

    /**
     * Unique Identifier for Room
     */
    @Column()
    uuid: string;

    /**
     * Room Name
     */
    @Column()
    roomName: string;

    /**
     * Room Description
     */
    @Column()
    description: string;

    /**
     * Room Visibility
     */
    @Column()
    visibility: string;

    /**
     * Room relation to User
     */
    @OneToOne(() => User)
    @JoinColumn()
    User: User;

}